#!/usr/bin/env bash
# `docs/backlog.md` is THE list. This is the only thing that reads it.
#
# ⚠️ Why this replaced two scripts. Until 2026-08-07 there were three open-item
# lists — `progress.md`'s generated roadmap table, `backlog.md`, and two hand
# tables in `activeContext.md` — and they disagreed in seventeen places. Worse,
# `unbuilt-asks.sh`, the script written to stop the three-session "where is my
# work?" repeat, matched `^### B2 —`/`^### B5 —` and rows shaped `^| <digits> |`.
# The reader's whole 2026-08-07 brief (§B9–§B19) and the holidays brief (§B7)
# are `##`-level with `H1`/`C1`/`S1` ids, so they were **structurally invisible
# to it** — it printed 2 items while ~30 of the reader's own asks sat open. A
# parser that silently returns nothing reads as "nothing outstanding", which is
# the most expensive lie this repo can tell itself.
#
# So the contract is rigid and **failure is loud**:
#
#   - `ID` STATUS `WAVE` `STREAM` `TIER` `gate:GATE` [`ask`] — **Title**
#         Free prose underneath, indented. Never parsed. The prose is the point.
#
# A line beginning "- `" that does not parse is a HARD ERROR, not a skip. A
# section carrying `| … |` table rows but no backlog rows is a HARD ERROR too —
# that is exactly how §B9–§B19 hid.
#
#   ./scripts/backlog.sh                # rewrite the generated index block
#   ./scripts/backlog.sh --check        # exit 1 if the index is stale (the gate)
#   ./scripts/backlog.sh --open         # every open row
#   ./scripts/backlog.sh --asks         # what the reader asked for and has NOT got
#   ./scripts/backlog.sh --next         # the next batch, with the model it needs
#   ./scripts/backlog.sh --tier mech    # a batch for one model tier
#   ./scripts/backlog.sh --stream chrome
#   ./scripts/backlog.sh --gate phone
#   ./scripts/backlog.sh --id B14       # one row and its prose
#   ./scripts/backlog.sh --json         # every row, for other scripts
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - "$@" <<'PY'
import re, sys, json, pathlib, collections

ARGS = sys.argv[1:]
DOC = pathlib.Path("docs/backlog.md")
BEGIN = "<!-- BACKLOG-INDEX:BEGIN — generated by scripts/backlog.sh, do not edit -->"
END = "<!-- BACKLOG-INDEX:END -->"

STATUS = {"⬜": "open", "◐": "part", "✅": "done", "❌": "wont"}
OPEN = ("open", "part")
WAVES = {
    "w0": "Blockers — tooling and truth",
    "w1": "Shipped but wrong",
    "w2": "Quick wins",
    "w3": "Substantial builds",
    "w4": "Complex, last",
}
# What each tier means in models. This table is the reader's batching request:
# a session works one tier at a time and says out loud when the tier changes.
TIERS = {
    "mech":   ("Opus 5 · medium", "exhaustive-switch sweeps, renames, one-line fixes, pointers"),
    "build":  ("Opus 5 · high", "ordinary feature work — a section, a card, an InputKind, a DataDomain"),
    "hard":   ("Opus 5 · xhigh/max", "calibration, statistics, anything moving a score's denominator"),
    "ultra":  ("Opus 5 · ultracode workflow", "research plus adversarial verification"),
    "design": ("Fable 5", "UI/UX shape and copy"),
}
TIER_ORDER = ["mech", "design", "build", "hard", "ultra"]

ROW = re.compile(
    r"^- `(?P<id>[^`]+)` (?P<status>[⬜◐✅❌]) "
    r"`(?P<wave>w[0-4])` `(?P<stream>[a-z0-9-]+)` `(?P<tier>[a-z]+)` "
    r"`gate:(?P<gate>[a-z]+(?::[^`]+)?)` (?P<ask>`ask` )?— (?P<title>.+)$"
)
LOOKS_LIKE_ROW = re.compile(r"^- `")

lines = DOC.read_text().splitlines()

rows, errors, section, in_generated, in_fence = [], [], "", False, False
sections = collections.OrderedDict()

# A section may opt out of the "tables must be rows" rule by declaring itself
# prose — but it has to say WHY, on the line. §A's answered questions are the
# real case: they are decisions already made, kept as prose precisely so a
# future session cannot re-ask them, and they are not work.
PROSE_ONLY = re.compile(r"<!--\s*backlog:\s*prose-only\s*—\s*.+?-->")

for n, line in enumerate(lines, 1):
    if line.startswith(BEGIN):
        in_generated = True
        continue
    if line.startswith(END):
        in_generated = False
        continue
    if in_generated:
        continue
    # A fenced block is illustration, not data — the contract is documented in
    # this very file with a worked example, and the example is not a row.
    if line.lstrip().startswith("```"):
        in_fence = not in_fence
        continue
    if in_fence:
        continue
    if PROSE_ONLY.search(line) and section:
        sections[section]["prose_only"] = True
    if line.startswith("## ") or line.startswith("### "):
        section = line.lstrip("# ").strip()
        sections.setdefault(section, {"rows": 0, "table": 0, "line": n,
                                      "prose_only": False})
    if LOOKS_LIKE_ROW.match(line):
        m = ROW.match(line)
        if not m:
            # ⚠️ The whole point. A row in the wrong shape is never skipped.
            errors.append(f"{DOC}:{n}: line starts a backlog row but does not "
                          f"match the contract:\n      {line[:150]}")
            continue
        d = m.groupdict()
        d.update(line=n, section=section, ask=bool(d["ask"]),
                 state=STATUS[d["status"]])
        rows.append(d)
        if section:
            sections[section]["rows"] += 1
    elif line.startswith("| ") and section:
        sections[section]["table"] += 1

# --- validation ------------------------------------------------------------
seen = {}
for r in rows:
    if r["id"] in seen:
        errors.append(f"{DOC}:{r['line']}: duplicate id `{r['id']}` "
                      f"(first at line {seen[r['id']]}). Ids are never reused.")
    seen[r["id"]] = r["line"]
    if r["tier"] not in TIERS:
        errors.append(f"{DOC}:{r['line']}: unknown tier `{r['tier']}` — "
                      f"expected one of {', '.join(TIERS)}")

for r in rows:
    if r["gate"].startswith("needs:"):
        for dep in r["gate"][len("needs:"):].split(","):
            if dep.strip() and dep.strip() not in seen:
                errors.append(f"{DOC}:{r['line']}: `{r['id']}` is gated on "
                              f"`{dep.strip()}`, which is not a row in this file.")

# A section full of `| … |` rows and no backlog rows is the §B9–§B19 failure
# happening again: a whole brief added in a shape the parser cannot see.
for name, s in sections.items():
    if s["rows"] == 0 and s["table"] >= 3 and not s.get("prose_only"):
        errors.append(
            f"{DOC}:{s['line']}: section \"{name}\" has {s['table']} table rows "
            f"and no backlog rows.\n      Every item must be a `- \\`ID\\` …` row "
            f"or this script cannot see it — which is exactly how §B7 and "
            f"§B9–§B19 stayed invisible to unbuilt-asks.sh.\n      If this "
            f"section is genuinely not work, say so on a line inside it:\n"
            f"      <!-- backlog: prose-only — why -->")

if errors:
    print(f"backlog: {len(errors)} problem(s) in {DOC}\n", file=sys.stderr)
    for e in errors:
        print(f"  ✗ {e}", file=sys.stderr)
    print("\n  Nothing was rewritten. Fix the rows above — a row this script "
          "cannot read is\n  a row the next session will never be shown.",
          file=sys.stderr)
    sys.exit(2)

open_rows = [r for r in rows if r["state"] in OPEN]

def fmt(r, width=88):
    t = re.sub(r"\*\*|`", "", r["title"]).strip()
    if len(t) > width:
        t = t[: width - 1].rstrip() + "…"
    return t

def show(rs, header):
    if not rs:
        print(f"{header}: nothing.")
        return
    print(f"{header} ({len(rs)}):\n")
    for r in sorted(rs, key=lambda r: (r["wave"], TIER_ORDER.index(r["tier"]) if r["tier"] in TIER_ORDER else 9, r["id"])):
        flag = " [asked for]" if r["ask"] else ""
        gate = "" if r["gate"] == "none" else f"  gate:{r['gate']}"
        mark = "◐ " if r["state"] == "part" else ""
        print(f"  {r['wave']}  {r['tier']:<6} {r['id']:<12} {mark}{fmt(r)}{gate}{flag}")

# --- queries ---------------------------------------------------------------
def arg_after(flag):
    return ARGS[ARGS.index(flag) + 1] if flag in ARGS and len(ARGS) > ARGS.index(flag) + 1 else None

if "--open" in ARGS:
    show(open_rows, "Open"); sys.exit(0)

if "--json" in ARGS:
    # For other scripts, so nothing has to re-implement ROW. `status.sh` reads
    # this: two copies of the row regex is how the three-list era started.
    print(json.dumps(rows)); sys.exit(0)

if "--asks" in ARGS:
    asks = [r for r in open_rows if r["ask"]]
    print("Things the reader asked for that are NOT built:\n")
    show(asks, "Asked for")
    print(f"\n  Read the row's prose in {DOC} before picking one up.")
    sys.exit(0)

if "--tier" in ARGS:
    t = arg_after("--tier")
    if t not in TIERS:
        print(f"backlog: unknown tier '{t}'. Known: {', '.join(TIERS)}", file=sys.stderr)
        sys.exit(2)
    model, what = TIERS[t]
    print(f"Tier `{t}` — **{model}** — {what}\n")
    show([r for r in open_rows if r["tier"] == t], f"Open at tier {t}")
    sys.exit(0)

if "--stream" in ARGS:
    s = arg_after("--stream")
    show([r for r in open_rows if r["stream"] == s], f"Open in stream {s}"); sys.exit(0)

if "--gate" in ARGS:
    g = arg_after("--gate")
    show([r for r in open_rows if r["gate"].split(":")[0] == g], f"Open with gate {g}"); sys.exit(0)

if "--id" in ARGS:
    want = arg_after("--id")
    hit = next((r for r in rows if r["id"] == want), None)
    if not hit:
        print(f"backlog: no row `{want}`", file=sys.stderr); sys.exit(1)
    print("\n".join(lines[hit["line"] - 1: hit["line"] + 24]).split("\n- `")[0])
    sys.exit(0)

if "--next" in ARGS:
    # The reader's ordering: fundamental problems, then quick wins, then the
    # complex work. Within a wave, batch by tier so a session changes model once.
    ready = [r for r in open_rows if r["gate"] == "none"]
    for w in WAVES:
        batch = [r for r in ready if r["wave"] == w]
        if not batch:
            continue
        print(f"Next: **{w} — {WAVES[w]}** ({len(batch)} ready, "
              f"{len([r for r in open_rows if r['wave'] == w]) - len(batch)} gated)\n")
        for t in TIER_ORDER:
            tb = [r for r in batch if r["tier"] == t]
            if not tb:
                continue
            model, _ = TIERS[t]
            print(f"  ── tier `{t}` — run these on **{model}** ──")
            for r in sorted(tb, key=lambda r: r["id"]):
                print(f"     {r['id']:<12} {fmt(r, 78)}{' [asked for]' if r['ask'] else ''}")
            print()
        print("  ⚠️ Say the model out loud before starting a tier that differs "
              "from the one you are running.")
        sys.exit(0)
    print("Next: nothing ungated is open. Run --gate phone / --gate decision.")
    sys.exit(0)

# --- the generated index ---------------------------------------------------
counts = collections.Counter(r["state"] for r in rows)
by_wave_tier = collections.Counter((r["wave"], r["tier"]) for r in open_rows)
by_gate = collections.Counter(r["gate"].split(":")[0] for r in open_rows)

out = [BEGIN, ""]
out.append(f"**{len(open_rows)} open** ({counts['open']} not started, "
           f"{counts['part']} part done) · {counts['done']} shipped · "
           f"{counts['wont']} will not be built. "
           f"Regenerate with `./scripts/backlog.sh`.")
out.append("")
out.append("| Wave | " + " | ".join(f"`{t}`" for t in TIER_ORDER) + " | Total |")
out.append("|---|" + "---|" * (len(TIER_ORDER) + 1))
for w, label in WAVES.items():
    cells = [str(by_wave_tier[(w, t)] or "") for t in TIER_ORDER]
    total = sum(by_wave_tier[(w, t)] for t in TIER_ORDER)
    if not total:
        continue
    out.append(f"| **{w}** {label} | " + " | ".join(cells) + f" | {total} |")
out.append("")
out.append("Gates on open rows: " + " · ".join(
    f"**{g}** {n}" for g, n in sorted(by_gate.items(), key=lambda kv: -kv[1])) + ".")
out.append("")
out.append("| # | Item | Wave | Tier | Gate |")
out.append("|---|---|---|---|---|")
for i, r in enumerate(sorted(open_rows, key=lambda r: (
        r["wave"], TIER_ORDER.index(r["tier"]) if r["tier"] in TIER_ORDER else 9, r["id"])), 1):
    title = fmt(r, 76).replace("|", "\\|")
    ask = " ⭐" if r["ask"] else ""
    out.append(f"| {i} | `{r['id']}` {title}{ask} | {r['wave']} | `{r['tier']}` | "
               f"{'' if r['gate'] == 'none' else r['gate']} |")
out.append("")
out.append("⭐ = the reader asked for this in their own words.")
out.append("")
out.append(END)
block = "\n".join(out)

doc = DOC.read_text()
if BEGIN not in doc or END not in doc:
    print(f"backlog: no BACKLOG-INDEX markers in {DOC}", file=sys.stderr)
    sys.exit(2)
current = doc[doc.index(BEGIN): doc.index(END) + len(END)]

if current == block:
    print(f"backlog: index up to date ({len(open_rows)} open, {len(rows)} rows)")
    sys.exit(0)
if "--check" in ARGS:
    print("backlog: the index at the top of docs/backlog.md no longer matches "
          "the rows below it.", file=sys.stderr)
    print("         Run ./scripts/backlog.sh.", file=sys.stderr)
    sys.exit(1)

DOC.write_text(doc.replace(current, block))
print(f"backlog: rewrote the index ({len(open_rows)} open of {len(rows)} rows)")
PY
