#!/usr/bin/env bash
# Derive the insight card's section order and features from the code, and keep
# `docs/card-sections.md` honest about them.
#
# Why generated rather than written: the previous version of that table was
# hand-maintained, and the session that added a section updated the code, the
# order comment and half the table. A 14-row list nobody can check by eye is
# exactly the shape `gen-symbol-index.sh` exists for, and the 17x17 matrix
# before it was wrong by one column until it was generated.
#
#   ./scripts/card-map.sh            # rewrite the generated block in the doc
#   ./scripts/card-map.sh --check    # exit 1 if the doc is out of date
#
# The block is delimited by CARD-MAP markers in docs/card-sections.md. Anything
# outside them — the rationale, the gaps, the chart audit — is written by hand
# and is never touched.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - "$@" <<'PY'
import re, sys, pathlib

CHECK = "--check" in sys.argv
VIEW = pathlib.Path("HealthInsights/Features/Insights/InsightDetailView.swift")
DOC = pathlib.Path("docs/card-sections.md")
BEGIN = "<!-- CARD-MAP:BEGIN — generated by scripts/card-map.sh, do not edit -->"
END = "<!-- CARD-MAP:END -->"

src = VIEW.read_text()

# The render order: the identifiers inside `if let result { ... } else {` in
# `body`, in the order they appear. Comments and the ViewAndAdd conditional are
# handled explicitly rather than by a cleverer regex — this file is read by
# people more often than by this script.
body = src[src.index("if let result {"):src.index("ContentUnavailableView")]
order = []
for line in body.splitlines():
    line = line.strip()
    if not line or line.startswith("//") or line.startswith("if ") or line in {"}", "{"}:
        continue
    m = re.match(r"^([A-Za-z][A-Za-z0-9]*)(\(result\)|\(\))?$", line)
    if m:
        order.append(m.group(1))
    else:
        # A section rendered as its own `View` type, with arguments — and
        # possibly spread over several lines, which the regex above cannot see.
        #
        # ⚠️ This used to be `elif line.startswith("ViewAndAddSection(")`: one
        # section, special-cased by name. The next section written that way
        # (`InstrumentAgreementSection`, backlog B3-23) was therefore dropped
        # from the map **without a word**, and `--check` reported the doc up to
        # date while the doc was missing a section. A generated map whose
        # generator silently skips input is worse than a hand-written one,
        # because nobody re-reads a table the script says is fine.
        #
        # Matching the *opening* line of the initialiser is enough: the
        # continuation lines are argument labels, which are lower-case and so
        # cannot match a capitalised type name.
        m = re.match(r"^([A-Z][A-Za-z0-9]*)\(", line)
        if m:
            order.append(m.group(1))

# Section titles, per declaring member. A member may render more than one
# title (the age chart is two cards' worth), so all of them are kept.
titles = {}
for match in re.finditer(r"(?:private |@ViewBuilder )*(?:private )?(?:func|var) "
                         r"([A-Za-z][A-Za-z0-9]*)\b", src):
    name = match.group(1)
    chunk = src[match.end():match.end() + 4000]
    found = re.findall(r'(?:InsightSection|NestedInsightSection)\(\s*(?:\n\s*)?title: "([^"]+)"',
                       chunk)
    # Stop at the next member declaration so titles aren't stolen from below.
    nxt = re.search(r"\n    (?:private |@ViewBuilder )*(?:private )?(?:func|var) ", chunk)
    if nxt:
        found = re.findall(
            r'(?:InsightSection|NestedInsightSection)\(\s*(?:\n\s*)?title: "([^"]+)"',
            chunk[:nxt.start()])
    if found:
        titles.setdefault(name, [])
        for title in found:
            if title not in titles[name]:
                titles[name].append(title)

HAND = {
    "headerCard": ["(the score itself — dial, headline, confidence, explanation)"],
    "timeframeBar": ["*(screen control, pinned above the tab bar)*"],
    "disclaimerCard": ["*(chrome, not a section)*"],
    "bespokeSection": ["*(one `switch`, per card — see the matrix)*"],
    "ViewAndAddSection": ["View & add"],
    "feedbackCard": ["Was this accurate?"],
    # Sections whose `InsightSection(title:)` lives in their own file, which
    # this script does not read.
    "InstrumentAgreementSection": ["Which instrument to believe"],
}

# The timeframe control is not in the scroll — it is a `safeAreaInset`, pinned
# above the tab bar — but leaving it out of the map would lose the record of a
# control that drives five sections. Appended rather than positioned, because it
# has no position: it is on screen the whole time.
if "timeframeBar" in src and "timeframeBar" not in order:
    order.append("timeframeBar")

rows = []
position = 0
for name in order:
    shown = titles.get(name) or HAND.get(name) or ["*(untitled)*"]
    chrome = name in {"timeframeBar", "disclaimerCard"}
    if not chrome:
        position += 1
    rows.append((("—" if chrome else str(position)), name, " · ".join(shown)))

table = ["| # | Renders | Section title |", "|---|---|---|"]
table += [f"| {n} | `{member}` | {shown} |" for n, member, shown in rows]
block = "\n".join([BEGIN, "", *table, "", END])

doc = DOC.read_text()
if BEGIN not in doc or END not in doc:
    print("card-map: no CARD-MAP markers in docs/card-sections.md", file=sys.stderr)
    sys.exit(2)
current = doc[doc.index(BEGIN):doc.index(END) + len(END)]

if current == block:
    print(f"card-map: up to date ({position} sections)")
    sys.exit(0)
if CHECK:
    print("card-map: docs/card-sections.md is out of date with "
          "InsightDetailView.body.", file=sys.stderr)
    print("          Run ./scripts/card-map.sh and review the rest of that "
          "file — a new or moved section changes the matrix and the feature "
          "audit too, and those are written by hand.", file=sys.stderr)
    sys.exit(1)

DOC.write_text(doc.replace(current, block))
print(f"card-map: rewrote the section map ({position} sections)")
PY
