#!/usr/bin/env bash
#
# Regenerate docs/symbol-index.md — one line per top-level type, so "where does
# X live" is a grep against 200 lines instead of a hunt through 15,000.
#
# Generated, never hand-written: a hand-maintained index rots, and a rotten
# index is worse than none because it is trusted.
#
#   ./scripts/gen-symbol-index.sh
#
# Run it after adding or moving a type. `scripts/verify.sh` warns when the index
# is stale.

set -euo pipefail
cd "$(dirname "$0")/.."

out=docs/symbol-index.md

{
    echo "# Symbol index"
    echo
    echo "_Generated by \`scripts/gen-symbol-index.sh\` — do not edit by hand._"
    echo
    echo "Every top-level type, and the file it lives in. The point is to answer"
    echo "\"where is X\" without reading \`architecture.md\` (700 lines) or grepping"
    echo "the tree. For *why* something is the way it is, that document is still"
    echo "the place to look."
    echo

    for root in InsightKit/Sources/InsightKit HealthInsights; do
        echo "## $root"
        echo
        # Group by directory so related types read together.
        find "$root" -name '*.swift' -type f | sort | while read -r file; do
            matches=$(grep -nE '^(public |internal |private |final |@MainActor |@Observable )*(struct|enum|class|actor|protocol|extension) [A-Z][A-Za-z0-9]*' "$file" 2>/dev/null \
                | grep -vE '(extension|^\s)' \
                | sed -E 's/^([0-9]+):.*(struct|enum|class|actor|protocol) ([A-Za-z0-9]+).*/\3|\1/' \
                | grep -E '^[A-Za-z0-9]+\|[0-9]+$' | sort -u -t'|' -k1,1 || true)
            [ -z "$matches" ] && continue
            printf -- '- `%s`\n' "${file#"$root"/}"
            printf '%s\n' "$matches" | while IFS='|' read -r name line; do
                printf -- '  - `%s` :%s\n' "$name" "$line"
            done
        done
        echo
    done
} > "$out"

echo "Wrote $out ($(grep -c '^  - ' "$out") types across $(grep -c '^- `' "$out") files)"
