#!/usr/bin/env bash
# Build the open-items table at the top of `docs/progress.md` from the roadmap
# itself, and keep it honest.
#
# Why generated rather than written: `docs/progress.md` is 1700 lines of prose
# and the open items are scattered through it — four sit inside `## Shipped`
# sections as unfinished clauses, seven are device-verification, the rest are
# under `## Next`. A reader asking "what is still open" had to grep for
# `- [ ]`, and a hand-written summary of a list that long is stale the first
# time somebody ticks a box.
#
#   ./scripts/roadmap-table.sh            # rewrite the generated block
#   ./scripts/roadmap-table.sh --check    # exit 1 if the table is out of date
#
# Same contract as `card-map.sh`: the block is delimited by ROADMAP-TABLE
# markers and everything outside them is hand-written and never touched. The
# rows come from lines starting `- [ ]` at column 0 — the same pattern
# `handover-check.sh` counts, so the table's length and the gate's number can
# never disagree.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - "$@" <<'PY'
import re, sys, pathlib

CHECK = "--check" in sys.argv
DOC = pathlib.Path("docs/progress.md")
BEGIN = "<!-- ROADMAP-TABLE:BEGIN — generated by scripts/roadmap-table.sh, do not edit -->"
END = "<!-- ROADMAP-TABLE:END -->"

# Which `##` an item sits under decides what kind of open it is. An unticked box
# inside `## Shipped` is a clause its own session left behind; one under
# `## In progress` needs the phone rather than a build.
GROUPS = {
    "Shipped": "loose end",
    "In progress / not yet device-verified": "device",
    "Next": "next",
}

lines = DOC.read_text().splitlines()

# An item's title can wrap — `**Nothing leaves the phone today, and that must
# stay true until the user opts in per signal.**` closes its bold on the second
# line — so gather the item's block before reading a title out of it.
def block_at(i):
    parts = [lines[i][len("- [ ] "):]]
    for line in lines[i + 1:]:
        if not line.strip() or not line.startswith(" "):
            break
        parts.append(line.strip())
    return " ".join(parts)

def title_of(text):
    bold = re.match(r"\*\*(.+?)\*\*", text)
    if bold:
        claim = bold.group(1)
        # A short bold lead is a label rather than a claim — `**Body
        # Composition** — the "view & add" scan entry` says nothing on its own,
        # so keep the clause it introduces. A lead that ends in a full stop is
        # already a sentence and is left alone.
        rest = re.match(r"\s*([—–:])\s*(.+)", text[bold.end():])
        if rest and len(claim) < 40:
            clause = re.split(r"(?<=[a-z)`\"])\. ", rest.group(2))[0]
            claim = f"{claim}{'' if rest.group(1) == ':' else ' '}{rest.group(1)} {clause}"
    else:
        claim = re.split(r"\s+[—–]\s+|(?<=[a-z)`])\. ", text)[0]
    claim = re.sub(r"\*\*|~~|\s+", lambda m: " " if m.group().isspace() else "", claim)
    claim = claim.strip().rstrip(".:,;")
    if len(claim) > 78:
        claim = claim[:77].rstrip() + "…"
    # Truncation and clause-splitting both leave orphaned brackets behind.
    if claim.count("(") > claim.count(")"):
        claim = claim[:claim.rindex("(")].strip().rstrip(",;") + "…"
    return claim.replace("|", "\\|")

rows = []
group = subsection = ""
for i, line in enumerate(lines):
    if line.startswith("## "):
        group, subsection = line[3:].strip(), ""
    elif line.startswith("### "):
        subsection = line[4:].strip()
    elif line.startswith("- [ ] "):
        if group not in GROUPS:
            continue
        where = subsection or group
        where = re.sub(r"\s*\(.*?\)\s*$", "", where).replace("|", "\\|")
        rows.append((GROUPS[group], where, title_of(block_at(i))))

table = ["| # | Open item | Section | Gate |", "|---|---|---|---|"]
table += [f"| {n} | {title} | {where} | {kind} |"
          for n, (kind, where, title) in enumerate(rows, 1)]
block = "\n".join([BEGIN, "", *table, "", END])

doc = DOC.read_text()
if BEGIN not in doc or END not in doc:
    print("roadmap-table: no ROADMAP-TABLE markers in docs/progress.md", file=sys.stderr)
    sys.exit(2)
current = doc[doc.index(BEGIN):doc.index(END) + len(END)]

if current == block:
    print(f"roadmap-table: up to date ({len(rows)} open items)")
    sys.exit(0)
if CHECK:
    print("roadmap-table: the table at the top of docs/progress.md no longer "
          "matches the roadmap below it.", file=sys.stderr)
    print("               Run ./scripts/roadmap-table.sh.", file=sys.stderr)
    sys.exit(1)

DOC.write_text(doc.replace(current, block))
print(f"roadmap-table: rewrote the open-items table ({len(rows)} open items)")
PY
